version: '3.8'
name: '${APP_NAME}'

configs:
  postgres_config:
    file: './postgres/postgres.conf'

services:
  postgres:
    image: '${POSTGRESQL_IMAGE}'
    environment:
      POSTGRES_DB: ${APP_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command:
      - -c
      - config_file=/etc/postgresql.conf
    configs:
      - source: postgres_config
        target: /etc/postgresql.conf
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 5432
    volumes:
      - ../../../dockerdata/postgres/:/var/lib/postgresql/data
    networks:
      - mynetwork

  electric:
    image: '${ELECTRIC_IMAGE}'
    init: true
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${APP_NAME}
      PG_PROXY_PASSWORD: ${PG_PROXY_PASSWORD}
      LOGICAL_PUBLISHER_HOST: ${LOGICAL_PUBLISHER_HOST}
      AUTH_MODE: insecure
    ports:
      - ${ELECTRIC_PORT}:5133
      - ${ELECTRIC_PROXY_PORT}:65432
    depends_on:
      - postgres
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
